version: "3"

services:
  oauth2:
    build: OAuth2/
    ports:
      - 8001:8001
    environment:
      # Время жизни токена доступа.
      ACCESS_TOKEN_EXPIRE_MINUTES: 10
      # Время жизни токена обновления.
      REFRESH_TOKEN_EXPIRE_MINUTES: 60
      # Соединение с базой данных.
      DB_CONNECT_STR: "sqlite:///db.sqlite3"

      # Пароли для пользователей при инициализации базы данных.
      INIT_ADMIN_PASSWORD: "Pups_555"
      INIT_SYSTEM_PASSWORD: "Pups_555"
      INIT_DIRECTOR_PASSWORD: "Pups_555"
      INIT_USER_PASSWORD: "Pups_555"

      DEBUG_MODE: "true"
      
    command: >
      sh -c "alembic upgrade head &&
      uvicorn main:app --host 0.0.0.0 --port 8001"

  oauth2_test:
    build: OAuth2_test/
    ports:
      - 8000:8000
    environment:
      # Хост микросервиса авторизации.
      AUTH_SERVER_HOST: "localhost"
      # Порт микросервиса авторизации.
      AUTH_SERVER_PORT: 8001

      DEBUG_MODE: "true"
      
    command: uvicorn main:app --host 0.0.0.0 --port 8000    
    network_mode: host
    
    depends_on:
      - oauth2
