"""Added User table

Revision ID: a3a2b6e8b9ad
Revises: 
Create Date: 2024-09-10 08:07:46.275818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from OAuth2.utils import init_users
from OAuth2.db.db_connection import session
from OAuth2.db.db_types import MyDateTime


# revision identifiers, used by Alembic.
revision: str = 'a3a2b6e8b9ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('status', sa.SMALLINT(), nullable=False),
    sa.Column('role', sa.SMALLINT(), nullable=False),
    sa.Column('date_joined', MyDateTime(), nullable=False),
    sa.Column('last_login', MyDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    init_users(session)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts_user')
    # ### end Alembic commands ###
